spring:
    application:
        name: open-api-project

    security:
        user:
            name: user
            password:

    datasource:
        url: jdbc:mysql://localhost:3306/open_api_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username:
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true